name: dawn_dart
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/knopp/skia_dart

environment:
  sdk: ^3.12.0-117.0.dev

resolution: workspace

dependencies:
  dawn_dart_api: ^0.1.0
  ffi: ^2.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  ffigen: ^20.1.1
